### ISSUE TITLE
README + process book + design doc

### ISSUE THREAD

**Issue by hnstr** [SimonIlic/project-psychic-waffle#1]
Blijf je README updaten. Als je meer informatie hebt gevonden over andere apps, zet dan de links naar die apps niet alleen in je process book, maar juist ook in je README. Maak je process book ook even netjes door de formatting aan te passen. 

Je design doc is nog onvolledig. Dit is vooral een overview van hoe de schermen naast elkaar werken, maar de database komt hier bijvoorbeeld niet in voor?

**Comment by SimonIlic** [comment]
Bedankt voor de tips! Ik ga vandaag verder aan de slag met de design doc.

> Als je meer informatie hebt gevonden over andere apps, zet dan de links naar die apps niet alleen in je process book, maar juist ook in je README.

Dit ging om het vorige app idee en is nu niet meer van toepassing (vandaar de quoted opmaak van de eerste 2 dagen)
